// Generated by gencpp from file go_arm/Mycaryolo.msg
// DO NOT EDIT!


#ifndef GO_ARM_MESSAGE_MYCARYOLO_H
#define GO_ARM_MESSAGE_MYCARYOLO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace go_arm
{
template <class ContainerAllocator>
struct Mycaryolo_
{
  typedef Mycaryolo_<ContainerAllocator> Type;

  Mycaryolo_()
    : xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)
    , conf(0.0)
    , name()
    , pose()  {
    }
  Mycaryolo_(const ContainerAllocator& _alloc)
    : xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)
    , conf(0.0)
    , name(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _xmin_type;
  _xmin_type xmin;

   typedef int64_t _ymin_type;
  _ymin_type ymin;

   typedef int64_t _xmax_type;
  _xmax_type xmax;

   typedef int64_t _ymax_type;
  _ymax_type ymax;

   typedef float _conf_type;
  _conf_type conf;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::go_arm::Mycaryolo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::go_arm::Mycaryolo_<ContainerAllocator> const> ConstPtr;

}; // struct Mycaryolo_

typedef ::go_arm::Mycaryolo_<std::allocator<void> > Mycaryolo;

typedef boost::shared_ptr< ::go_arm::Mycaryolo > MycaryoloPtr;
typedef boost::shared_ptr< ::go_arm::Mycaryolo const> MycaryoloConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::go_arm::Mycaryolo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::go_arm::Mycaryolo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::go_arm::Mycaryolo_<ContainerAllocator1> & lhs, const ::go_arm::Mycaryolo_<ContainerAllocator2> & rhs)
{
  return lhs.xmin == rhs.xmin &&
    lhs.ymin == rhs.ymin &&
    lhs.xmax == rhs.xmax &&
    lhs.ymax == rhs.ymax &&
    lhs.conf == rhs.conf &&
    lhs.name == rhs.name &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::go_arm::Mycaryolo_<ContainerAllocator1> & lhs, const ::go_arm::Mycaryolo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace go_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::go_arm::Mycaryolo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::go_arm::Mycaryolo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::go_arm::Mycaryolo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::go_arm::Mycaryolo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::go_arm::Mycaryolo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::go_arm::Mycaryolo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::go_arm::Mycaryolo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7bc5135cea8e008feca35aa2219ecd3";
  }

  static const char* value(const ::go_arm::Mycaryolo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7bc5135cea8e008ULL;
  static const uint64_t static_value2 = 0xfeca35aa2219ecd3ULL;
};

template<class ContainerAllocator>
struct DataType< ::go_arm::Mycaryolo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "go_arm/Mycaryolo";
  }

  static const char* value(const ::go_arm::Mycaryolo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::go_arm::Mycaryolo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 xmin\n"
"int64 ymin\n"
"int64 xmax\n"
"int64 ymax\n"
"\n"
"float32 conf\n"
"\n"
"string name\n"
"geometry_msgs/Pose pose  \n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::go_arm::Mycaryolo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::go_arm::Mycaryolo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.xmax);
      stream.next(m.ymax);
      stream.next(m.conf);
      stream.next(m.name);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mycaryolo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::go_arm::Mycaryolo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::go_arm::Mycaryolo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "xmin: ";
    Printer<int64_t>::stream(s, indent + "  ", v.xmin);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ymin: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ymin);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "xmax: ";
    Printer<int64_t>::stream(s, indent + "  ", v.xmax);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ymax: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ymax);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "conf: ";
    Printer<float>::stream(s, indent + "  ", v.conf);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GO_ARM_MESSAGE_MYCARYOLO_H
